### ISSUE TITLE
cypress-tests runs on new pull request

### ISSUE THREAD

**Issue by jakereal** [welsh-revenue-authority/component-library#106]
Hi,

Thought of a feature request for you new Cypress CI. Might be good to run it whenever someone makes a pull request to check that no regressions happen.

Docs about it here, https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request

```yaml
on:
  pull_request:
    types: [opened, reopened]
```
